# basic port 4002
# prisma-basic port 4003
# dataloader port 4005
# joinmonster port 4006
url: http://192.168.1.21:4001/
headers:
  Content-Type: application/json
queries:
  - name: GetAllMovies
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    connections: 1
    query: |
      query Movies {
        movies {
          id
          title
          rating
        }
      }
  - name: GetActionMoviesCategory
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    connections: 1
    query: |
      query Query($category: String!) {
        moviesByCategory(category: $category) {
          id
          title
          rating
          categories {
            type
          }
        }
      }
    variables:
      {
        category: "action"
      }
  - name: GetActionMoviesCategoryCharacters
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    connections: 1
    query: |
      query Query($category: String!) {
        moviesByCategory(category: $category) {
          id
          title
          rating
          categories {
            type
          }
          characters {
            character
          }
        }
      }
    variables:
      {
        category: "action"
      }
  - name: GetActionMoviesCategoryCharactersActors
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    connections: 1
    query: |
      query Query($category: String!) {
        moviesByCategory(category: $category) {
          id
          title
          rating
          categories {
            type
          }
          characters {
            character
            played_by {
              id
              first_name
              last_name
            }
          }
        }
      }
    variables:
      {
        category: "action"
      }
  - name: GetActionMoviesCategoryCharactersActorsManus
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    connections: 1
    query: |
      query Query($category: String!) {
        moviesByCategory(category: $category) {
          id
          title
          rating
          categories {
            type
          }
          characters {
            character
            played_by {
              id
              first_name
              last_name
              manuscripts {
                id
                year
              }
            }
          }
        }
      }
    variables:
      {
        category: "action"
      }
