# basic port 4001
# dataloader port 4004
url: http://localhost:4004/
headers:
  Content-Type: application/json
queries:
  - name: GetActionMovieWithCharacterActorMoviesManuscripts
    tools: [autocannon, k6]
    execution_strategy: REQUESTS_PER_SECOND
    rps: 10
    duration: 10s
    query: |
      query MoviesByCategory($category: String!) {
        moviesByCategory(category: $category) {
          id
          rating
          title
          categories {
            type
          }
          characters {
            character
            played_by {
              id
              first_name
              last_name
              manuscripts {
                year
              }
            }
          }
        }
      }
    variables:
      {
        category: "action"
      }
