url: http://192.168.1.21:4000/
headers:
  Content-Type: application/json
queries:
  - name: GetAllMovies
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    query: |
      query Movies {
        movies {
          id
          title
          rating
        }
      }
  - name: GetActionMoviesCategory
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    query: |
      query Query($where: MovieWhere) {
        movies(where: $where) {
          id
          title
          rating
          categories {
            type
          }
        }
      }
    variables:
      {
        "where": {
          "categories_SOME": {
            "type": "action"
          }
        }
      }
  - name: GetActionMoviesCategoryCharacters
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    query: |
      query Query($where: MovieWhere) {
        movies(where: $where) {
          id
          title
          rating
          categories {
            type
          }
          charactersConnection {
            edges {
              properties {
                character
              }
            }
          }
        }
      }
    variables:
      {
        "where": {
          "categories_SOME": {
            "type": "action"
          }
        }
      }
  - name: GetActionMoviesCategoryCharactersActors
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    query: |
      query Query($where: MovieWhere) {
        movies(where: $where) {
          id
          title
          rating
          categories {
            type
          }
          charactersConnection {
            edges {
              properties {
                character
              }
              node {
                id
                first_name
                last_name
              }
            }
          }
        }
      }
    variables:
      {
        "where": {
          "categories_SOME": {
            "type": "action"
          }
        }
      }
  - name: GetActionMoviesCategoryCharactersActorsManus
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 10
    query: |
      query Query($where: MovieWhere) {
        movies(where: $where) {
          id
          title
          rating
          categories {
            type
          }
          charactersConnection {
            edges {
              properties {
                character
              }
              node {
                id
                first_name
                last_name
                manuscripts {
                  id
                  year
                }
              }
            }
          }
        }
      }
    variables:
      {
        "where": {
          "categories_SOME": {
            "type": "action"
          }
        }
      }
